name: Cleanup Docs Preview

on:
  pull_request:
    types: [closed]
    branches:
      - main2
    paths:
      - 'docs/**'
      - 'tools/github_readme_sync/**'
      - '.github/workflows/docs_preview.yml'

jobs:
  cleanup_docs_preview:
    name: cleanup-docs-preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout tbp.monty
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          path: tbp.monty

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install miniconda
        run: |
          if [ ! -d ~/miniconda ]
          then
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -b -p ~/miniconda
            rm ~/miniconda.sh
          fi
          export PATH="$HOME/miniconda/bin:$PATH"
          conda --version

      - name: Create conda environment
        working-directory: tbp.monty
        run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          (conda env list | grep tbp.monty) && conda remove --name tbp.monty --all --yes || true
          conda env create
          source activate tbp.monty
          pip install -e .[dev,github_readme_sync_tool,print_version_tool]

      - name: Get version and branch
        id: preview_info
        uses: ./tbp.monty/.github/actions/get_preview_info

      - name: Delete docs preview
        working-directory: tbp.monty
        run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          source activate tbp.monty
          export README_API_KEY=${{ secrets.README_API_KEY }}
          python -m tools.github_readme_sync.cli delete "${{ steps.preview_info.outputs.monty_version }}-${{ steps.preview_info.outputs.branch_name }}" 