name: Docs Preview

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  # TODO: switch to pull_request_target before merging
  pull_request:
    branches:
      # TODO: move back to main before merging
      - main2
    paths:
      - 'docs/**'
      - 'tools/github_readme_sync/**'
      - '.github/workflows/docs_preview.yml'

permissions:
  pull-requests: write

jobs:
  deploy_docs_preview:
    name: deploy-docs-preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tbp.monty
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          path: tbp.monty

      - name: Create initial PR comment
        uses: ./tbp.monty/.github/actions/pin_comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          comment_id: docs-preview
          working_directory: tbp.monty
          message: |
            📚 **Documentation Preview**

            Building documentation preview... ⏳

            Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for progress.
      - name: Generate cache key
        id: generate_cache_key
        run: |
          mkdir -p ~/tbp
          ln -s $GITHUB_WORKSPACE/tbp.monty ~/tbp/tbp.monty
          shasum -a 256 ~/tbp/tbp.monty/environment_arm64.yml | awk '{print $1}' > ~/tbp/environment_arm64.sha
          shasum -a 256 ~/tbp/tbp.monty/environment.yml | awk '{print $1}' > ~/tbp/environment.sha
          shasum -a 256 ~/tbp/tbp.monty/pyproject.toml | awk '{print $1}' > ~/tbp/pyproject.toml.sha
          echo "monty-${RUNNER_OS}-$(cat ~/tbp/environment_arm64.sha)-$(cat ~/tbp/environment.sha)-$(cat ~/tbp/pyproject.toml.sha)" > ~/tbp/conda_env_cache_key.txt
          echo "conda_env_cache_key_sha=$(cat ~/tbp/conda_env_cache_key.txt | shasum -a 256 | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Restore cache
        id: restore_cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/miniconda
          key: ${{ steps.generate_cache_key.outputs.conda_env_cache_key_sha }}
          lookup-only: true

      - name: Install miniconda
        if: steps.restore_cache.outputs.cache-hit != 'true'
        run: |
          if [ ! -d ~/miniconda ]
          then
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -b -p ~/miniconda
            rm ~/miniconda.sh
          fi
          export PATH="$HOME/miniconda/bin:$PATH"
          conda --version
      - name: Save cache
        if: steps.restore_cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/miniconda
          key: ${{ steps.restore_cache.outputs.cache-primary-key }}

      - name: Create conda environment
        if: steps.restore_cache.outputs.cache-hit != 'true'
        working-directory: tbp.monty
        run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          # Configure conda for faster downloads
          conda config --set channel_priority flexible
          
          # Install faster conda solver
          conda install -n base conda-libmamba-solver -y
          
          # Remove existing environment if it exists
          (conda env list | grep tbp.monty) && conda remove --name tbp.monty --all --yes || true
          
          # Create environment with parallel downloads
          CONDA_EXPERIMENTAL_SOLVER=libmamba conda env create
          source activate tbp.monty
          pip install -e .[dev,github_readme_sync_tool,print_version_tool]
      - name: Get version and branch
        id: preview_info
        uses: ./tbp.monty/.github/actions/get_preview_info

      - name: Deploy docs
        working-directory: tbp.monty
        run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          source activate tbp.monty
          export README_API_KEY=${{ secrets.README_API_KEY }}
          export IMAGE_PATH=${{ vars.IMAGE_PATH }}
          python -m tools.github_readme_sync.cli upload docs "${{ steps.preview_info.outputs.monty_version }}-${{ steps.preview_info.outputs.branch_name }}"

      - name: Update PR comment on success
        if: success()
        uses: ./tbp.monty/.github/actions/pin_comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          comment_id: docs-preview
          working_directory: tbp.monty
          message: |
            📚 **Documentation Preview**

            ✅ A preview of the documentation changes in this PR is available for *maintainers only* here:
            ${{ vars.DOCS_URL_PREFIX }}v${{ steps.preview_info.outputs.monty_version }}-${{ steps.preview_info.outputs.branch_name }}

            Last updated: ${{ steps.preview_info.outputs.monty_date }}
      - name: Update PR comment on failure
        if: failure()
        uses: ./tbp.monty/.github/actions/pin_comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          comment_id: docs-preview
          working_directory: tbp.monty
          message: |
            📚 **Documentation Preview**

            ❌ Failed to build documentation preview.

            Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
